name = "xai-finance"
compatibility_date = "2025-04-25"

[build]
command = "pnpm run build"

[site]
bucket = ".next/static"
entry-point = "."

[env.production]
routes = [
  { pattern = "*/*", zone_name = "xai-finance" }
] 