name = "xai-finance-worker"
compatibility_date = "2025-04-25"
main = "src/index.ts"

[build]
command = "pnpm run build"

[site]
bucket = ".next"

[env.production]
routes = [
  { pattern = "xai-finance.workers.dev/*", zone_name = "xai-finance" }
]

[assets]
directory = ".next" 