name = "xai6-worker"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-04-25"
main = "src/worker.ts"

[build]
command = "pnpm run build"

[site]
bucket = ".next/static"

[env.production]
routes = [
  { pattern = "xai-finance.workers.dev/*", zone_name = "xai-finance" }
]

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "82142229e1314340b69c1622bb5282f8"
