name = "xai-finance"
compatibility_date = "2025-04-25"
main = "index.js"

[build]
command = "pnpm run build"

[site]
bucket = ".next"
entry-point = "."

[env.production]
routes = [
  { pattern = "*/*", zone_name = "xai-finance" }
]

[assets]
directory = ".next" 